version: '3'

services:
  bot-docker:
    image: kseniac/ec2-agonyofcalculus
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      TOKEN: "5065674481:AAGDYE16kYOn49f0-lFSJpISgF-0348dV6I"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope myscope
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"